#!/bin/bash

#EOC
#------------------------------------------------------------------------------
#                  GEOS-Chem Global Chemical Transport Model                  !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: copy-cannon-env
#
# !DESCRIPTION: Script to distribute startup files from the env repository
#  to the appropriate location in your home directory.
#\\
#\\
# !CALLING SEQUENCE:
#  Type at the command-line prompt:
#
#    ./copy-cannon-env
#EOP
#------------------------------------------------------------------------------
#BOC

#-----------------------------------------------------------
# Copy contents of env/bin
#-----------------------------------------------------------
if [ -d ${HOME}/bin ]; then
  # Copy contents of env/bin to your bin directory
  cp -v ./bin/* ${HOME}/bin/
else
  # Copy entire env/bin directory to your home directory
  cp -rv ./bin ${HOME}
fi

#-----------------------------------------------------------
# Copy contents of env/IDL
#-----------------------------------------------------------
if [ -d ${HOME}/IDL ]; then
  # Copy contents of env/IDL to your IDL directory
  cp -v ./IDL/* ${HOME}/IDL/
else
  # Create IDL directory and copy
  cp -rv ./IDL ${HOME}
fi

#-----------------------------------------------------------
# Copy contents of env/envs
#-----------------------------------------------------------
if [ -d ${HOME}/envs ]; then
  # Copy contents of env/envs to your envs directory
  cp -v ./envs/* ${HOME}/envs/
else
  # Create envs directory and copy
  cp -rv ./envs ${HOME}
fi

#-----------------------------------------------------------
# Copy contents of env/root
#-----------------------------------------------------------
cp -v ./root/.bash_profile ${HOME}
cp -v ./root/.login        ${HOME}
cp -v ./root/.tmux.conf    ${HOME}
cp -v ./root/.bashrc       ${HOME}

# Only copy the following files if they do not exist.
# If the files already exist, you will need to manually bring in changes
# to avoid removing your personal settings.
if [ ! -f ${HOME}/.my_personal_settings ]; then
  cp -v ./.my_personal_settings ${HOME}
else
  echo "./.my_personal_settings was not copied. Update this file manually."
  echo "If your are getting set up for the first time type:"
  echo "  cp -v ./my_personal_settings ${HOME}"
  echo " "
fi
if [ ! -f ${HOME}/.emacs ]; then
  cp -v ${HOME}/env/root/.emacs ${HOME}
else
  echo "./.emacs was not copied. Update this file manually."
  echo "If your are getting set up for the first time type:"
  echo "  cp -v ./.emacs ${HOME}"
  echo " "
fi
if [ ! -f ${HOME}/.Xresources ]; then
  cp -v ./root/.Xresources ${HOME}
else
  echo "$root/.Xresources was not copied. Update this file manually."
  echo "If your are getting set up for the first time type:"
  echo "  cp -v ./.Xresources ${HOME}"
  echo " "
fi

# Exit normally
exit 0
