#!/bin/tcsh

# $Id: startup,v 1.2 2009/08/13 18:09:13 bmy Exp $
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !MODULE: startup
#
# !DESCRIPTION: Shell script STARTUP launches applications at startup.  
#  STARTUP is meant to be called from a Secure CRT login window on one of 
#  the Harvard Atmospheric Chemistry Modeling Group machines.  This allows 
#  you to define a Windows firewall with X11 tunneling. 
#\\
#\\
# !CALLING SEQUENCE:
#  startup
#
# !REVISION HISTORY: 
#  01 Oct 2003 - R. Yantosca - Initial version
#  13 Aug 2009 - R. Yantosca - Removed obsolete commands
#  13 Aug 2009 - R. Yantosca - Added ProTeX header
#EOP
#------------------------------------------------------------------------------
#BOC

# Force a mount with "who" commmand
ssh bmy@argus  who
ssh bmy@sol    who
ssh bmy@rhea   who

# Open connections to several machines (add others if you want)
# Delay each window by a few seconds to avoid problems w/ .Xauthority
$home/bin/xt -h argus    &
sleep 3
$home/bin/xt -h sol      &
sleep 3
$home/bin/xt -h rhea     &
sleep 3
$home/bin/xt -h rhea     &

# Open an EMACS window
emacs &

# Exit normally
exit(0)
#EOC
