#!/bin/tcsh

#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !MODULE: startup
#
# !DESCRIPTION: Shell script STARTUP launches applications at startup.  
#  STARTUP is meant to be called from a Secure CRT login window on one of 
#  the Harvard Atmospheric Chemistry Modeling Group machines.  This allows 
#  you to define a Windows firewall with X11 tunneling. 
#\\
#\\
# !CALLING SEQUENCE:
#  startup
#
# !REMARKS:
#  You also need an .Xdefaults file with xterminal settings (such as the
#  one that Bob Yantosca has set up).
#
# !REVISION HISTORY: 
#  01 Oct 2003 - R. Yantosca - Initial version
#  13 Aug 2009 - R. Yantosca - Removed obsolete commands
#  13 Aug 2009 - R. Yantosca - Added ProTeX header
#  05 Mar 2010 - R. Yantosca - Modified for new keys
#  05 Jun 2012 - R. Yantosca - Modified for bmy@bmy.as.harvard.edu
#  21 Jun 2012 - R. Yantosca - Now use xterm instead of xt, since we are
#                              already logged into the same system
#EOP
#------------------------------------------------------------------------------
#BOC

# Force a mount with the who command
ssh -A bmy@bmy.as.harvard.edu  who

# Open connections to several Xterms
xterm -n $user &      # Login window #1
sleep 3

xterm -n $user &      # Login window #2
sleep 3 

xterm -n $user &      # Login window #3
sleep 3 

# Open an EMACS window
emacs &

# Exit normally
exit(0)
#EOC
