#!/bin/bash

#------------------------------------------------------------------------------
#                  GEOS-Chem Global Chemical Transport Model                  !
#------------------------------------------------------------------------------
#BOP
#
# !MODULE: run_geos_chem
# 
# !DESCRIPTION: Runs a GEOS-Chem "classic" simulation on Odyssey.
#\\
#\\
# !REMARKS:
#  This script submits a typical 4x5 GEOS-Chem "classic" simulation 
#  (i.e.using OpenMP serial parallelization) on Odyssey.  A 4x5 fullchem 
#  simulation will take about 8 GB of RAM in total, across all CPUs.  (Your
#  simulation may use more memory, especially if you are saving out a lot
#  of diagnostic output.)  
#
#  In this script we are requesting 8 CPUs with 1000 MB/CPU, for a total 
#  of 8 GB of RAM. For higher-resolution runs, you may have to increase the
#  amount of memory per CPU.
#
#  The available partitions (i.e. run queues) are:
#  (1) jacob
#  (2) general 
#  (3) unrestricted 
#  (4) interactive 
#  (5) serial_requeue 
#  (6) bigmem
# 
#  The available options for email notification are:
#  (1) BEGIN : When the job starts
#  (2) END   : When the job finishes
#  (3) FAIL  : If the job dies with an error
#  (4) ALL   : (1), (2), and (3) combined
#
#  Alternative SLURM option keywords:
#  (1) Instead of -n 8    you can also use --ntasks=8
#  (2) Instead of -N 1    you can also use --nodes=1
#  (3) Instead of -t 2880 you can also use --time=2880
#
# !REVISION HISTORY: 
#  05 Dec 2014 - R. Yantosca - Initial version, based on Lu Hu's script
#  16 Jul 2015 - M. Sulprizio- Now use jacob partition by default 
#EOP
#------------------------------------------------------------------------------
#BOC

# Settings for the SLURM scheduler
#SBATCH -n 8                                # Number of CPUs you are requesting
#SBATCH -N 1                                # Ask for all CPUs on the same node
#SBATCH -t 720                              # Runtime in minutes (minimum: 10)
#SBATCH -p jacob                            # Partition to submit to (see above)
#SBATCH --mem-per-cpu=1000                  # Memory per cpu in MB. 
#SBATCH -o geoschem.out                     # File where stdout will be written
#SBATCH -e geoschem.err                     # File where stderr will be written
#SBATCH --mail-type=END                     # Type of email notification
#SBATCH --mail-user=<YOUR_EMAIL_ADDRESS>    # Your email address

# Set the proper # of threads for OpenMP
# This must match the number you set with -n above!
export OMP_NUM_THREADS=8

# GEOS-Chem output log file name
log=v10-01.log

# Run GEOS-Chem; pipe output to log
# Remove any prior log files w/ the same name
rm -f $log

# Run GEOS_Chem
./geos.mp > $log

# Exit normally
exit 0
#EOC
